name: Golang CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.x, 1.11.x, 1.12.x, 1.13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Lint with diff
        run: diff -u <(echo -n) <(gofmt -d .)
      - name: Test with go test
        run: go test -v -race ./...
      - name: Build with go
        run: go build ./...
